### ISSUE TITLE
Provide possibility to calculate global values in force functors

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#100]
**Is your feature request related to a problem? Please describe.**
The calculation of the potential energy or the virial (needed to calculate the pressure) is a pairwise interaction and is often done in the main kernel call, i.e. within the pairwise functors.
For the correct calculation of these global values, you have to make certain that contributions are not summed up multiple times. This is currently not easily possible.

**Describe the solution you'd like**
Provide an easy way to calculate these values correctly.
Multiple options exist:
1. Multiply the global results by 1/2. This is possible only if no newton3 optimization is performed. (also only for full-shell if boundary evaluations are not calculated more than 2 times)
2. Provide a boolean to the functor calls that specifies whether the current interaction should contribute to the global values. This can be done 
   1. cell-pair wise:
   Problems for: direct-sum + verlet-lists
   2. particle-pair wise:
   Problem: relatively expensive
3. Use the eighth shell traversal + decomposition scheme.
   Problems for: direct-sum.
   Problem: a force-exchange needs to be implemented by the user.

**The problems**
- Direct-Sum(2.i. + 3.): Here the problem arises because only 1 halo cell exists. For the correct handling of the outer particle pairs (cell-wise), 26 halo cells are needed.
- Verlet-Lists(2.ii.): Once the verlet-lists are generated, it becomes ambiguous to differentiate particle-pair-interactions that contribute to the global values and those that don't. A speedy implementation probably needs a separate verlet list storage for interactions that don't contribute to the global values.

**Edit**:
**Current Solution**
Do it functor based.

**Implementation State for the LJFunctor**
- [x] LJFunctor: AoS noomp -- #102 
- [x] LJFunctor: AoS omp -- #113 
- [x] LJFunctor: SoA noomp -- #127
- [x] LJFunctor: SoA omp -- #127
- [ ] LJ Functor: Verlet-Lists SoA

**Comment by SteffenSeckler** [comment]
current solution (WIP) for LJFunctor:
particle-pair-wise, BUT:
not every time step, as it is not needed that often anyways.
