### ISSUE TITLE
Finish VerletClusterLists

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#155]
VerletClusterLists is not yet finished. 
**Todo's**:
- [x] iteratePairwiseAoS with newton3 enabled. -- here an openmp scheme has to be found. -> #295 
- [ ] halo particle handling:
  - [ ] updateContainer needs to be parallelized
  - [x] halo particles have to be marked, otherwise they can not be differentiated from leaving particles. (as long as they are saved over multiple steps).
  - [ ] addParticle might need to be changed.
  - [ ] addHaloParticle needs to be implemented.
    - [ ] reenable TraversalComparison for halo particles.
  - [ ] deleteHaloParticles needs to be implemented.
  - [ ] updateHaloParticle needs to be implemented.
  - [x] The RegionParticleIterator needs to be implemented. Might make use of: [std::upper_bound](https://en.cppreference.com/w/cpp/algorithm/upper_bound) and [std::lower_bound](https://en.cppreference.com/w/cpp/algorithm/lower_bound) or alternatively [std::equal_range](https://en.cppreference.com/w/cpp/algorithm/equal_range)
  - [x] Implement Traversal
- [ ] enable ContainerConversionTest for VerletClusterLists
- [ ] Deletion of particles is not implemented
- [ ] Particles passed to 'addParticle()' are only really added in the next rebuild. Up until then, also the iterators don't iterate over them. (This breaks e.g. the container conversion test. It does not fail, but silently loses all particles.)
- [ ] OpenMP chunk sizes aren't optimized.
- [ ] iterators are ignoring the iterator behavior -> VERY WRONG!

**Comment by HobbyProgrammer** [comment]
Notes for after #319 is merged besides halo stuff that is still not implemented:

- Deletion of particles is not implemented

- Particles passed to 'addParticle()' are only really added in the next rebuild. Up until then, also the iterators don't iterate over them. (This breaks e.g. the container conversion test. It does not fail, but silently loses all particles.)
- OpenMP chunk sizes aren't optimized.
