### ISSUE TITLE
AutoPas and const correctness

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#250]
**Describe the bug**
Currently, AutoPas doesn't handle const correctness at all.
E.g. using a `const AutoPas&` will result in more or less all interfaces disappearing because of the missing const keyword after the function declaration.

**Subtasks**
- [x] Put const after all getters in:
  - [x] the AutoPas class.
  - [x] the Container classes.
  - [x] Particle classes.
- [x] Implement const_iterator(s). This is probably best done using a template for the ParticleIterator's, which then point to const particles and don't allow deletion
