### ISSUE TITLE
Implement Linked-Cells like interface

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#460]
**Is your feature request related to a problem? Please describe.**
The Verlet-like interface produces a couple of problems:
- Particles are sometimes inside of a container, even though you wouldn't expect it. (You have to iterate a farther than a domain of a particle is long)
- The position of particles can only be made conform to periodic boundary conditions when the container is rebuilt.
- Particles can only be added and deleted in steps where the container is rebuilt
- Tuning and Rebuilding across MPI ranks are not fixed but have to be synchronized. So flexible tuning is not possible.

**Describe the solution you'd like**
A linked-cells like interface:
- Particles are stored inside of the AutoPas object they belong to.

This has the following advantages:
- Particles can be added and deleted at every step.
- Particles are conforming to boundaries.
- Verlet rebuild frequency could be made variable.
- Flexible tuning.
- No synchronization across MPI-Ranks needed.

**Implementation Details**
The idea is to still maintain the structure of the container, i.e., the particles are neither added nor deleted from the internal container.
As particles are still added and deleted to the AutoPas object (not the container) the following is needed:
- [x] Add an **additional vector**(or other structure) of particles:
    - This vector holds particles that should not be added to the container, as the container would be made invalid if they are added.
    - Theoretically, one could check whether it is safe to add a particle to the internal container and add it if it is. If it is not safe, then one adds the particle to the additional vector.
    - Possibly two vectors instead of one are better (one for owned, one for halo particles)
    - [x] The additional vector needs to participate in the force calculation!
    - [x] Iterators (or for_each #434) have to consider the additional vector.
- [x] Particles need to be "removable" from a container:
    - This can be done by marking particles as a dummy
         - either by moving the position far enough away from the domain or marking them via a flag (e.g. make the bool `owned` an enum)
- [x] Special care has to be taken if a particle that has previously been halo is added as an owned particle, as interactions with another particle could appear twice (once with the OLD halo and once with the newly added particle)! For this purpose, all halo particles should be marked as dummy after an updateContainer() call. This would make it consistent with Linked Cells.

**Possible problems**
Performance might be slower:
- <strike>some optimizations in Linked-Cells cannot be made (potentially no cell-wise owned state), this happens because particles can suddenly be dummies.</strike> This is no longer valid.
- Leaving particles have to be communicated at every step. This can no longer be skipped.

**Describe alternatives you've considered**
Leave as is.

**Additional context**

**Comment by SteffenSeckler** [comment]
Just looked at this PR, as I am writing about the interface and updated this Issue:
- Dummy state has already been introduced.
- Particle iterators can already handle an additional vector (was needed for VerletClusterLists).
